tws_check_update, style indentations

diff --git a/tws_check_update b/tws_check_update
--- a/tws_check_update
+++ b/tws_check_update
@@ -29,30 +29,30 @@ cd "${TDIR}" || exit 1
 
 for FILE_MIRROR in $FILES_TO_MIRROR; do
 	FILE_CUR="${DOWNLOAD_DIR}/${FILE_MIRROR}"
-# create fake sparse file for wget because wget -K is broken and -O file
-# conflicts with -N
-if test -f "${FILE_CUR}" ; then
-	truncate -r "${FILE_CUR}" "${FILE_MIRROR}"
-	touch -r "${FILE_CUR}" "${FILE_MIRROR}"
-fi
 
-if wget --no-verbose -N -P "${TDIR}" "${URL_MIRROR}/${FILE_MIRROR}" ;then 
+	# create fake sparse file for wget because wget -K is broken and -O file
+	# conflicts with -N
+	if test -f "${FILE_CUR}" ; then
+		truncate -r "${FILE_CUR}" "${FILE_MIRROR}"
+		touch -r "${FILE_CUR}" "${FILE_MIRROR}"
+	fi
 
-    if test "${FILE_MIRROR}" -nt "${FILE_CUR}" ; then
-        echo "TWS needs update" 1>&2
-        WARN=1
-        MAIL_SUBJECT="${MAIL_SUBJECT}, update available!"
-	DST="$(get_perm_file_name "${FILE_MIRROR}")"
-        mv "${FILE_MIRROR}" "${DOWNLOAD_DIR}/${DST}"
-	ln -sf "${DST}" "${FILE_CUR}"
-    else
-        echo "TWS is uptodate" 1>&2
-    fi
-else
-    echo "check for update failed" 1>&2
-    WARN=1;
-    MAIL_SUBJECT="${MAIL_SUBJECT}, check for update failed!"
-fi
+	if wget --no-verbose -N -P "${TDIR}" "${URL_MIRROR}/${FILE_MIRROR}" ;then 
+		if test "${FILE_MIRROR}" -nt "${FILE_CUR}" ; then
+			echo "TWS needs update" 1>&2
+			WARN=1
+			MAIL_SUBJECT="${MAIL_SUBJECT}, update available!"
+			DST="$(get_perm_file_name "${FILE_MIRROR}")"
+			mv "${FILE_MIRROR}" "${DOWNLOAD_DIR}/${DST}"
+			ln -sf "${DST}" "${FILE_CUR}"
+		else
+			echo "TWS is uptodate" 1>&2
+		fi
+	else
+		echo "check for update failed" 1>&2
+		WARN=1;
+		MAIL_SUBJECT="${MAIL_SUBJECT}, check for update failed!"
+	fi
 done
 
 if test -n "$WARN" && test -n "$TO_ADDRESS"; then
