_check_update: add error messages at exit

diff --git a/tws_check_update b/tws_check_update
--- a/tws_check_update
+++ b/tws_check_update
@@ -22,12 +22,6 @@ URLS_TO_MIRROR="
 # use "tws_get_version" from the same directory as this scripts
 TWS_GET_VERSION="$(dirname "$(readlink -f "$0")")/tws_get_version"
 
-err_exit()
-{
-	echo "error: $1" 1>&2
-	exit 1
-}
-
 get_perm_file_name()
 {
 	local ver;
@@ -38,12 +32,13 @@ get_perm_file_name()
 }
 
 if ! test -d "${DOWNLOAD_DIR}" ;then
-	err_exit "${DOWNLOAD_DIR} does not exist"
+	echo "error: "${DOWNLOAD_DIR}" does not exist" 1>&2
+	exit 1
 fi
 
-TDIR="$(mktemp -d -t twsdl.XXXX)" || err_exit "fatal"
+TDIR="$(mktemp -d -t twsdl.XXXX)" || exit 1
 trap "rm -rf ${TDIR}" exit
-cd "${TDIR}" || err_exit "fatal"
+cd "${TDIR}" || exit 1
 
 for URL in $URLS_TO_MIRROR; do
 	FILE_MIRROR="$(basename "${URL}")"
